CREATE TABLE Users (
    id BIGINT PRIMARY KEY,
    FIRST_NAME VARCHAR(255) NOT NULL,
    LAST_NAME VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    STREET_ADDRESS VARCHAR(255) NOT NULL,
    CITY VARCHAR(255) NOT NULL,
    STATE VARCHAR(255) NOT NULL,
    ZIP_CODE BIGINT NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    USER_TYPE VARCHAR(255) NOT NULL DEFAULT 'Customer'
);

CREATE TABLE Cart (
    id BIGINT PRIMARY KEY,
    USER_ID BIGINT NOT NULL,
    COMPLETED BOOLEAN NOT NULL DEFAULT FALSE,
    FOREIGN KEY (USER_ID) REFERENCES Users(id)
);

CREATE TABLE Products (
    id BIGINT PRIMARY KEY,
    NAME_OF_PRODUCT VARCHAR(255) NOT NULL,
    IMAGE BIGINT NOT NULL,
    PRICE BIGINT NOT NULL
);

CREATE TABLE Sizes (
    id BIGINT PRIMARY KEY,
    Size VARCHAR(255) NOT NULL
);

CREATE TABLE Cart_Items (
    id BIGINT PRIMARY KEY,
    CART_ID BIGINT NOT NULL,
    PRODUCT_ID BIGINT NOT NULL,
    QUANTITY BIGINT NOT NULL,
    SIZE_ID BIGINT NOT NULL,
    FOREIGN KEY (CART_ID) REFERENCES Cart(id),
    FOREIGN KEY (PRODUCT_ID) REFERENCES Products(id),
    FOREIGN KEY (SIZE_ID) REFERENCES Sizes(id)
);

CREATE TABLE Past_Purchases (
    id BIGINT PRIMARY KEY,
    DATE DATE NOT NULL,
    SIZE_ID BIGINT NOT NULL,
    PRODUCT_ID BIGINT NOT NULL,
    CUSTOMER_ID BIGINT NOT NULL,
    PRICE_PAID BIGINT NOT NULL,
    FOREIGN KEY (SIZE_ID) REFERENCES Sizes(id),
    FOREIGN KEY (PRODUCT_ID) REFERENCES Products(id),
    FOREIGN KEY (CUSTOMER_ID) REFERENCES Users(id)
);

CREATE TABLE Picture_Gallery (
    id BIGINT PRIMARY KEY,
    URL VARCHAR(255) NOT NULL,
    CAPTION VARCHAR(255) NOT NULL,
    CUSTOMER_ID BIGINT NOT NULL,
    APPROVED BOOLEAN NOT NULL DEFAULT FALSE,
    FOREIGN KEY (CUSTOMER_ID) REFERENCES Users(id)
);

CREATE TABLE Dad_Quotes (
    id BIGINT PRIMARY KEY,
    QUOTE VARCHAR(255) NOT NULL,
    AUTHOR VARCHAR(255) NOT NULL
);
